---
deployment:
  tasks:
    # 1️⃣ Define deployment paths
    - export FRONTEND_PATH=/home/anjonixg/public_html
    - export BACKEND_PATH=/home/anjonixg/backend

    # 2️⃣ Build the Vite + React frontend
    - cd my-company-site
    - npm install --legacy-peer-deps
    - npm run build

    # 3️⃣ Deploy the built frontend to public_html
    - /bin/cp -R dist/* $FRONTEND_PATH

    # 4️⃣ Deploy backend files to backend folder
    - cd ..
    - mkdir -p $BACKEND_PATH
    - /bin/cp -R backend/* $BACKEND_PATH

    # 5️⃣ (Optional) Restart your backend (if using Node.js app)
    #    If you’re using Passenger or PM2, uncomment the relevant command below:
    # - touch $BACKEND_PATH/tmp/restart.txt
    # - pm2 restart all

    # ✅ Clean log
    - echo "🚀 Deployment completed successfully!"
