---
deployment:
  tasks:
    # 1️⃣ Define deployment paths
    - export FRONTEND_PATH=/home/anjonixg/public_html
    - export BACKEND_PATH=/home/anjonixg/backend

    # 2️⃣ Build the Vite + React frontend (abort if it fails)
    - cd my-company-site
    - echo "📦 Installing dependencies..."
    - npm install --legacy-peer-deps || { echo "❌ npm install failed. Aborting."; exit 1; }

    - echo "🏗️ Building Vite React app..."
    - npm run build || { echo "❌ Vite build failed. Deployment aborted."; exit 1; }

    # 3️⃣ Deploy the built frontend to public_html (only if build succeeded)
    - echo "🚀 Copying frontend files to $FRONTEND_PATH..."
    - /bin/cp -R dist/* $FRONTEND_PATH || { echo "❌ Failed to copy frontend files."; exit 1; }

    # 4️⃣ Deploy backend files to backend folder
    - cd ..
    - echo "🔧 Deploying backend files..."
    - mkdir -p $BACKEND_PATH
    - /bin/cp -R backend/* $BACKEND_PATH || { echo "❌ Failed to copy backend files."; exit 1; }

    - echo "🧾 Deployed files in frontend path ($FRONTEND_PATH):"
    - ls -lh $FRONTEND_PATH

    - echo "🧾 Deployed files in backend path ($BACKEND_PATH):"
    - ls -lh $BACKEND_PATH

    # 5️⃣ (Optional) Restart your backend (if using Node.js app)
    # Uncomment if using Passenger:
    # - touch $BACKEND_PATH/tmp/restart.txt
    #
    # Or if using PM2:
    # - pm2 restart all

    # ✅ All done
    - echo "✅ Deployment completed successfully at $(date)"
